package com.example.compose

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF5D4CBF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE5DEFF)
val md_theme_light_onPrimaryContainer = Color(0xFF190064)
val md_theme_light_secondary = Color(0xFF7F4894)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF8D8FF)
val md_theme_light_onSecondaryContainer = Color(0xFF320046)
val md_theme_light_tertiary = Color(0xFF6B4EA2)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEBDDFF)
val md_theme_light_onTertiaryContainer = Color(0xFF260059)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE5E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF48454F)
val md_theme_light_outline = Color(0xFF78767F)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFC8BFFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF5D4CBF)
val md_theme_light_outlineVariant = Color(0xFFC9C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFC8BFFF)
val md_theme_dark_onPrimary = Color(0xFF2E1190)
val md_theme_dark_primaryContainer = Color(0xFF4531A6)
val md_theme_dark_onPrimaryContainer = Color(0xFFE5DEFF)
val md_theme_dark_secondary = Color(0xFFECB2FF)
val md_theme_dark_onSecondary = Color(0xFF4C1662)
val md_theme_dark_secondaryContainer = Color(0xFF65307A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF8D8FF)
val md_theme_dark_tertiary = Color(0xFFD3BBFF)
val md_theme_dark_onTertiary = Color(0xFF3C1D70)
val md_theme_dark_tertiaryContainer = Color(0xFF533688)
val md_theme_dark_onTertiaryContainer = Color(0xFFEBDDFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF48454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC9C5D0)
val md_theme_dark_outline = Color(0xFF928F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inversePrimary = Color(0xFF5D4CBF)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFC8BFFF)
val md_theme_dark_outlineVariant = Color(0xFF48454F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF9888FF)
